export const site = {
  name: 'ANON CAT',
  description: 'Nine lives. None of your business. A privacy-minded cat inspired by Monero.',
  headline: ['NINE LIVES.', 'NONE OF YOUR', 'BUSINESS.'],
  intro: 'You found the cat. That’s all you get.',
  moneroLine: 'A privacy-minded cat inspired by Monero.',
  navigation: [{label:'The cat',href:'#file'}, {label:'The instinct',href:'#ethos'}, {label:'The hideout',href:'#artwork'}],
  moneroUrl: 'https://www.getmonero.org/get-started/what-is-monero/',
  socials: [] as { label: string; url: string }[],
  network: null as { name: string; documentationUrl: string } | null,
  purchaseUrl: null as string | null,
  assetIdentifier: null as string | null,
  file: [{label:'Name',value:'Not volunteered.'},{label:'Occupation',value:'Cat.'},{label:'Address',value:'Somewhere comfortable.'},{label:'Current plans',value:'Unavailable.'},{label:'Favorite color',value:'That one is obvious.'}],
  assets: {hero:'/assets/character/hero-cat.webp',step:'/assets/character/step-cat.webp',peek:'/assets/character/peek-cat.webp',seated:'/assets/character/seated-cat.webp',background:'/assets/environments/hideout-back.webp',foreground:'/assets/environments/hideout-front.webp',mobile:'/assets/environments/hideout-mobile.webp'},
} as const;
